# Generated by Django 5.2.1 on 2025-06-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('is_cleaner', 'Cleaner'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
