# Generated by Django 5.2.1 on 2025-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('is_cleaner', 'Cleaner'), ('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
