# Generated by Django 5.2.1 on 2025-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('taken', 'Taken')], default='booked', max_length=10),
        ),
    ]
