# Generated by Django 5.2.1 on 2025-06-02 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapprest", "0002_organization_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="service",
            new_name="services",
        ),
    ]
