# Generated by Django 5.2.1 on 2025-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0002_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('taken', 'Taken')], default='booked', max_length=10),
        ),
    ]
