# Generated by Django 5.2.1 on 2025-06-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapprest", "0003_rename_service_organization_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("suspended", "Suspended"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
