# Generated by Django 5.2.1 on 2025-06-20 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0004_alter_servicerequest_status_cleanerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanerrequest',
            name='organization',
        ),
        migrations.AddField(
            model_name='cleanerrequest',
            name='service_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapprest.servicerequest'),
        ),
    ]
