# Generated by Django 5.2.1 on 2025-06-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0005_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='message',
        ),
    ]
