# Generated by Django 5.2.1 on 2025-06-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0005_remove_cleanerrequest_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
