# Generated by Django 5.2.1 on 2025-06-21 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0007_cleanerrating_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('completed_at', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='cleaning_reports/')),
                ('client_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_reports', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_reports', to='myapprest.servicerequest')),
            ],
        ),
        migrations.DeleteModel(
            name='CleanerRating',
        ),
    ]
