# Generated by Django 5.2.1 on 2025-06-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0008_remove_cleaner_organization_cleaner_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.AddField(
            model_name='organization',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='organization_files/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
