# Generated by Django 5.2.1 on 2025-06-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0009_cleaningreport_forwarded_alter_servicerequest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanerrating',
            name='comment',
        ),
    ]
