# Generated by Django 5.2.1 on 2025-06-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0010_alter_organization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='bathrooms',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='bedrooms',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='guest',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
