# Generated by Django 5.2.1 on 2025-06-30 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0010_remove_cleanerrating_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningreport',
            name='client_rating',
        ),
    ]
