# Generated by Django 5.2.1 on 2025-06-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0011_remove_organization_organization_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='guest',
            new_name='guests',
        ),
    ]
