# Generated by Django 5.2.1 on 2025-06-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0012_rename_guest_organization_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
