# Generated by Django 5.2.1 on 2025-06-17 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0013_servicerequest_end_date_servicerequest_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaner',
            name='user',
        ),
        migrations.AddField(
            model_name='cleaner',
            name='auth_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_cleaners', to=settings.AUTH_USER_MODEL),
        ),
    ]
